Repository grm34/ZenMaxBuilder, pull requests merged in 2022-05, with the labels that each got.

#249 ZMB: Auto define CROSS_COMPILE in Makefile (TC)
  README.md
  docs/index.md
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/main.sh
  src/manager.sh
  src/prompter.sh
Labels: enhancement

#255 GH: Updates ZMB Contributing Guidelines (MD)
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#256 LANG: Adds German Language (100%)
  lang/de.cfg
Labels: enhancement, translation

#257 LANG: Adds German Language (100%)
  lang/de.cfg
Labels: enhancement, translation

#258 LANG: Updates German line length (TERM)
  lang/de.cfg
Labels: translation

#259 GH: Adds translation progress (MD)
  .github/CONTRIBUTING.md
Labels: documentation, translation

#268 ZMB: Fix command logging on retry (MAKE)
  src/manager.sh
  src/telegram.sh
Labels: bug

#273 ZMB: Fix RUN_AGAIN last failed command (unset)
  SECURITY.md
  src/prompter.sh
Labels: bug

#276 ZMB: Adds Lineage-GCC Toolchain (LOS)
  README.md
  SECURITY.md
  docs/_config.yml
  docs/index.md
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/maker.sh
  src/options.sh
  src/prompter.sh
  src/requirements.sh
Labels: enhancement, toolchain

#278 ZMB: Updates toolchain options (CFLAGS)
  etc/settings.cfg
Labels: toolchain

#279 ZMB: Fix settings changed warning on update (DIFF)
  src/options.sh
Labels: bug

#282 LANG: Updates Terminal Window Size ERR (min 76x12)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
Labels: translation

#283 ZMB: Fix forgotten Compiler Mandatory (MAIN)
  src/main.sh
Labels: bug

#284 GHS: Updates ZMB Statistics (v1.9)
  SECURITY.md
Labels: documentation

#286 ZMB: Improved defconfig Management (untouched)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/maker.sh
  src/prompter.sh
Labels: enhancement

#287 TG: Updates Host Core Count Message (MAKE)
  src/telegram.sh
Labels: telegram

#288 DOC: Adds Telegram Feedback Screenshot (MD)
  README.md
  docs/assets/images/telegram.jpg
  docs/index.md
Labels: telegram

#289 CONF: Updates Toolchains CFLAGS (MAKE)
  etc/settings.cfg
Labels: toolchain

#291 ZMB: Improved CROSS_COMPILE Management (MAKE)
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/main.sh
  src/maker.sh
  src/options.sh
  src/prompter.sh
Labels: enhancement

#303 ZMB: Fix Toolchain $PATH export (MAKE)
  etc/settings.cfg
  src/maker.sh
Labels: bug

#304 ZMB: Fix Link Time Optimization PATH (LTO)
  etc/settings.cfg
  src/maker.sh
Labels: bug, toolchain, fixed

#305 CONF: Adds Toolchain Compiler Comments (TC)
  etc/settings.cfg
Labels: documentation, toolchain

#306 ZMB: Updates Settings Comments (v2.0-beta)
  etc/settings.cfg
Labels: documentation, settings

#309 ZMB: Use of realpath to fix kernel dir assignment (CC)
  src/maker.sh
  src/prompter.sh
Labels: bug, toolchain

#310 ZMB: Adds ZenMaxBuilder main logo (2.0-beta)
  README.md
  docs/assets/images/zmb.png
  docs/index.md
Labels: documentation

#315 ZMB: ensure NO assignments in CFG files (TC)
  etc/settings.cfg
  src/maker.sh
Labels: bug, settings

#316 ZMB: Improved dependencies management (2.0-beta)
  README.md
  docs/index.md
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/flasher.sh
  src/options.sh
  src/prompter.sh
  src/requirements.sh
Labels: enhancement

#321 ZMB: Option to OFF dependencies auto installation
  etc/settings.cfg
  src/requirements.sh
Labels: enhancement, settings

#324 DOC: Updates ZMB Warning (MD)
  README.md
  SECURITY.md
  docs/index.md
Labels: documentation

#327 GHS: Updates to v2.0-beta1 (ZMB)
  README.md
  SECURITY.md
  docs/index.md
Labels: documentation

#328 LANG: Updates English Translation (ZMB)
  lang/en.cfg
Labels: translation

#329 ZMB: Fix ill-defined toolchain realpaths (MAIN)
  README.md
  SECURITY.md
  docs/index.md
  etc/settings.cfg
  src/main.sh
  src/maker.sh
Labels: bug, toolchain, fixed

#331 ZMB: Fix broken GCC detection on TERMUX (REQ)
  SECURITY.md
  etc/excluded.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/main.sh
  src/questioner.sh
  src/requirements.sh
Labels: bug, fixed

#332 LANG: Updates translation (v2.0-beta2)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/requirements.sh
Labels: translation

#333 ZMB: Adds kernel compilation debug mode (OPT)
  README.md
  SECURITY.md
  docs/index.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/main.sh
  src/maker.sh
  src/manager.sh
  src/options.sh
  src/questioner.sh
Labels: enhancement

#334 DOC: Updates ZMB Code Comments (v2.0-beta2)
  SECURITY.md
  src/main.sh
  src/maker.sh
  src/manager.sh
  src/options.sh
  src/questioner.sh
  src/requirements.sh
  src/telegram.sh
  src/zip.sh
Labels: documentation

#335 GHP: Adds ZMB Table of Contents (MD)
  README.md
  docs/index.md
Labels: documentation

#340 SHELL: Fix ZMB Realpath Detection (dirname)
  src/main.sh
Labels: bug

#344 DOC: Updates ZMB Description (MD)
  README.md
  docs/_config.yml
Labels: documentation

#345 ZMB: Fix Proton-GCC $PATH Verification (MAKE)
  src/maker.sh
Labels: bug, fixed

#347 ZMB: Fix Toolchains Realpaths on Update (OPT)
  src/maker.sh
  src/options.sh
Labels: bug, fixed

#350 ZMB: Fix CC Compiler not found (SED)
  src/maker.sh
Labels: bug, toolchain

#354 ZMB: Removes empty device folders on exit (MAN)
  src/manager.sh
Labels: enhancement

#356 ZMB: Fix CC output when defined in a condition
  src/maker.sh
Labels: bug, fixed

#357 ZMB: Fix the more recent file comparison with build start time
  src/main.sh
Labels: bug

#360 ZMB: Makes CC spaces replacement literal (SED)
  src/maker.sh
  src/telegram.sh
Labels: toolchain, main, Makefile

#362 GHP: Updates kernel-builder.com (v2.0-beta4)
  README.md
  docs/_config.yml
  docs/index.md
Labels: documentation

#363 ZMB: Use of ENV to invoke bash (SHEBANG)
  src/main.sh
  src/maker.sh
  src/manager.sh
  src/options.sh
  src/questioner.sh
  src/requirements.sh
  src/telegram.sh
  src/zip.sh
Labels: main

#364 ZMB: Adds ERR while CC not found in Makefile (SED)
  SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/maker.sh
Labels: toolchain, Makefile

#366 ZMB: Assigns execution permissions (SRC)
  src/maker.sh
  src/manager.sh
  src/options.sh
  src/questioner.sh
  src/requirements.sh
  src/telegram.sh
  src/zip.sh
Labels: main

#373 GH: ToC relative URLs for portability across forks
  README.md
Labels: documentation

#374 ZMB: Append CC to make command-line arguments (MK)
  src/maker.sh
Labels: toolchain, make cmd

#375 ZMB: Redesign ZMB into a single script file (BASH)
  .github/CONTRIBUTING.md
  README.md
  SECURITY.md
  docs/index.md
  src/main.sh
  src/maker.sh
  src/manager.sh
  src/options.sh
  src/questioner.sh
  src/requirements.sh
  src/telegram.sh
  src/zip.sh
  src/zmb.sh
  zmb
Labels: main

#377 ZMB: Removes forgotten test strings (DEV)
  src/zmb.sh
Labels: bug, fixed

#378 ZMB: Updates bash identation (v2.0)
  SECURITY.md
  src/zmb.sh
Labels: main

#379 GH: Updates MIT License (ZMB v2.0)
  LICENSE
  src/zmb.sh
Labels: documentation

#380 GH: Updates Security Policy (ZMB v2.0)
  SECURITY.md
Labels: documentation

#381 DOC: Updates ZMB Code Comments (v2.0)
  src/zmb.sh
Labels: documentation

#387 ZMB: Adds option to include files in AK3 (ZIP)
  etc/settings.cfg
  src/zmb.sh
Labels: enhancement

#391 ZMB: Adds Telegram API Url into user settings
  etc/settings.cfg
  src/zmb.sh
Labels: telegram, settings

#392 ZMB: Fix bad function call (clean AK3)
  src/zmb.sh
Labels: bug, fixed

#395 LANG: Reorder language strings (ZMB v2.0)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: translation

#396 DOC: Updates Overview & Warning (MD)
  README.md
  docs/index.md
Labels: documentation

#402 ZMB: Ensure default shell settings (SH)
  SECURITY.md
  etc/settings.cfg
  src/zmb.sh
Labels: main

#404 ZMB: Redesign main process for better readability
  SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: main

#406 DOC: Updates ZMB main process (title)
  src/zmb.sh
Labels: documentation

#411 ZMB: Fix build sending while not signed (TG)
  src/zmb.sh
Labels: bug, telegram, fixed

#413 SHELL: Updates Code Rendering TAB (2)
  src/zmb.sh
Labels: main

#414 CFG: Updates Code Rendering TAB (2)
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
Labels: translation, settings

#415 EXCLUDED: Updates Code Rendering TAB (2)
  etc/excluded.cfg
Labels: settings

#416 TG: Adds Photo/Audio/Video/Document Support (CURL)
  src/zmb.sh
Labels: telegram

#417 ZMB: Fix TG status on KILL (MAKE)
  src/zmb.sh
Labels: bug, telegram, fixed, main

#418 SHELL: Print error and debug messages to STDERR (ENV)
  src/zmb.sh
Labels: main

#419 SHELL: Updates CASE statement alternatives (CS)
  SECURITY.md
  src/zmb.sh
Labels: main

#420 SHELL: Quotes everything that needs to be (CS)
  src/zmb.sh
Labels: main

#421 SHELL: Fix <prevent sourcing> (return)
  src/zmb.sh
Labels: bug, fixed

#422 ZMB: Better clone AK3 with requirements (process)
  src/zmb.sh
Labels: requirements, AK3

#424 ZMB: Updates kernel patches (OPT)
  patches/drivers-media-dvb-usb-af9005-request_firmware.patch
  patches/kali-wifi-injection-3.12.patch
  patches/kali-wifi-injection-3.14.patch
  patches/kali-wifi-injection-3.16.patch
  patches/kali-wifi-injection-3.18.patch
  patches/kali-wifi-injection-4.0.patch
  patches/kali-wifi-injection-4.1.patch
  patches/kali-wifi-injection-4.14.patch
  patches/kali-wifi-injection-4.16.patch
  patches/kali-wifi-injection-4.4.patch
  patches/kali-wifi-injection-4.9.patch
  patches/kali-wifi-injection-5.15.patch
  patches/kali-wifi-injection-5.4.patch
  patches/kali-wifi-injection-5.9.patch
  patches/mac80211-3.4.patch
  patches/mac80211-3.8.patch
  patches/mac80211-backports.patch
  patches/mac80211.patch
  patches/remove-ports-restrictions.patch
  patches/rtl8187-injection-AP.patch
  patches/security-perf-allow-further-restriction-of-perf_event_open.patch
  patches/wireless-carl9170-Enable-sniffer-mode-promisc-flag-t.patch
Labels: patches

#427 ZMB: Updates user settings (CS)
  etc/settings.cfg
Labels: settings

#428 DOC: Updates user settings sections (center)
  etc/settings.cfg
Labels: settings

#431 SHELL: Avoids the use of eval (REQ)
  src/zmb.sh
Labels: main, requirements

#432 ZMB: Fix ARM32 > COMPAT while Linux > 4.2 (clang)
  src/zmb.sh
Labels: bug, toolchain, fixed, Proton-Clang, Proton-GCC

#435 SHELL: Ensure autocd & extglog deactivated (MAIN)
  src/zmb.sh
Labels: main

#436 ZMB: Adds global exit codes (BASH)
  SECURITY.md
  src/zmb.sh
Labels: main

#438 SHELL: Updates local/global VAR (log)
  etc/patterns.cfg
  src/zmb.sh
Labels: main

#439 ZMB: Fix user settings error msg (duplicate)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: bug, translation, fixed

#440 DOC: Adds missing returns (comments)
  SECURITY.md
  src/zmb.sh
Labels: documentation

#441 ZMB: Improves File Upload Management (TG)
  SECURITY.md
  etc/patterns.cfg
  etc/settings.cfg
  src/zmb.sh
Labels: enhancement, telegram

#442 DOC: Updates main title (ZMB)
  README.md
Labels: documentation

#443 GHP: Updates ZMB assets (WEB)
  README.md
  docs/assets/images/banner.png
  docs/assets/images/favicon.png
  docs/assets/images/kali.png
  docs/assets/images/zmb.png
  docs/index.md
Labels: website

#449 GHP: Really Fix Spoiler Screenshots (HTML)
  docs/index.md
Labels: website

#450 ZMB: Adds the Compiler Options in DEBUG Mode (MAIN)
  SECURITY.md
  src/zmb.sh
Labels: main

#453 ZMB: Management of animation and voice files (TG)
  SECURITY.md
  etc/patterns.cfg
  src/zmb.sh
Labels: telegram

#455 ZMB: Local AK3 banner (ZIP)
  docs/ak3/banner
  src/zmb.sh
Labels: AK3

#456 ZMB: Auto Repo Sync Local Forks (MAIN)
  .github/up2date/ak3_sync.yml
  .github/up2date/gcc-arm64_sync.yml
  .github/up2date/gcc-arm_sync.yml
  .github/up2date/los-arm64_sync.yml
  .github/up2date/los-arm_sync.yml
  .github/up2date/proton-clang_sync.yml
  .github/up2date/zenmaxx_sync.yml
  .github/up2date/zipsigner_sync.yml
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: settings, main, Proton-Clang, Eva-GCC, Lineage-GCC, Proton-GCC, ZipSigner, AK3

#457 ZMB: Fix Toolchains Install (REQ)
  src/zmb.sh
Labels: bug, toolchain, fixed

#462 ZMB: Local scopes to freed up memory (BASH)
  .github/workflows/gitlab-ci.yml
  SECURITY.md
  etc/patterns.cfg
  src/zmb.sh
Labels: bug, fixed

#464 ZMB: Really FIX File Recognition (Telegram)
  SECURITY.md
  etc/patterns.cfg
  src/zmb.sh
Labels: bug, telegram, fixed

#465 ZMB: Add option to show toolchains versions (OPT)
  README.md
  docs/index.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: enhancement, toolchain

#466 LANG: Fix German inverted string in #465
  lang/de.cfg
Labels: bug, translation, fixed

#468 ZMB: No exit timeout on manual options (MAN)
  src/zmb.sh
Labels: settings, main

#469 ZMB: Updates Code Count [#468]
  SECURITY.md
Labels: documentation

#472 ZMB: Fix libtool (not found)
  etc/settings.cfg
Labels: bug, fixed, requirements

#473 DOC: Updates requirements list (MD)
  README.md
  docs/index.md
Labels: documentation

#474 DOC: Updates "default" sections (settings)
  etc/settings.cfg
Labels: documentation

#475 ZMB: Fix "settings has changed" warning (update)
  SECURITY.md
  src/zmb.sh
Labels: documentation

#476 ZMB: Ensure Compiler is System supported (linker)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: toolchain

#478 ZMB: GNU-Clang Compiler (System GCC)
  SECURITY.md
  etc/settings.cfg
  src/zmb.sh
Labels: enhancement, toolchain

#480 ZMB: Fix unwanted check (readelf)
  src/zmb.sh
Labels: bug

#481 ZMB: GNU-Clang Compiler (system GCC)
  SECURITY.md
  etc/settings.cfg
  src/zmb.sh
Labels: enhancement, toolchain

#482 ZMB: Adds AOSP Clang from Google (TC)
  .gitignore
  README.md
  SECURITY.md
  docs/index.md
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: enhancement, toolchain, testing

#483 Adds possibilty to update AOSP-Clang
  README.md
  docs/index.md
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: toolchain, testing

#484 Adds AOSP-Clang update notes (--update)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: toolchain, AOSP-Clang

#485 LLVM Binutils from Google for AOSP-Clang
  .gitignore
  README.md
  SECURITY.md
  docs/index.md
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: enhancement, toolchain, testing, AOSP-Clang

#486 DOC: Updates ZMB Screenshots (MD)
  README.md
  docs/assets/images/help.png
  docs/index.md
Labels: documentation

#489 Fix Telegram sending while file extension < 3
  src/zmb.sh
Labels: bug, telegram, fixed

#491 DOC: Updates toolchains section (MD)
  README.md
  SECURITY.md
  docs/index.md
  etc/settings.cfg
  src/zmb.sh
Labels: documentation

#495 Fix previous crap German Translation 🔥
  lang/de.cfg
Labels: translation, fixed

#497 AOSP tag only on Toolchain update for old version
  src/zmb.sh
Labels: toolchain

#498 DOC: Split export/kernelversion for readability
  src/zmb.sh
Labels: documentation

#499 Fix TG Adobe Illustrator Artwork sending (img)
  SECURITY.md
  src/zmb.sh
Labels: telegram

#501 Improves PLATFORM_VERSION management (TG)
  SECURITY.md
  src/zmb.sh
Labels: telegram

#502 Do not check package manager install (expect required)
  src/zmb.sh
Labels: requirements

#503 Prevent running as root (MAIN)
  SECURITY.md
  src/zmb.sh
Labels: main

#505 CONFIG_DEBUG_SECTION_MISMATCH in DEBUG Mode
  SECURITY.md
  src/zmb.sh
Labels: make cmd

#506 Improves toolchain linker check (readelf)
  SECURITY.md
  etc/settings.cfg
  src/zmb.sh
Labels: toolchain, settings, testing

#507 Adds secondary expressions to ensure matchs
  src/zmb.sh
Labels: main

#508 Enforced secondary regex to prevent false positive
  src/zmb.sh
Labels: main

#509 Enable/Disable TC Linker Check from settings
  SECURITY.md
  etc/settings.cfg
  src/zmb.sh
Labels: toolchains, settings

#510 Rewrite Toolchains Options (MAKE)
  SECURITY.md
  etc/settings.cfg
  src/zmb.sh
Labels: toolchains, settings, main, testing

#511 DOC: Center the Titles of the Sections (code comments)
  src/zmb.sh
Labels: documentation

#512 Improves Terminal window management (size)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: enhancement, translation

#514 Adds Neutron-Clang Toolchain (by @dakkshesh07)
  README.md
  SECURITY.md
  docs/index.md
  etc/settings.cfg
  src/zmb.sh
Labels: enhancement, testing, Neutron-Clang, Neutron-GCC

#517 Rewrite patch function (OPTION)
  SECURITY.md
  src/zmb.sh
Labels: main

#518 Fix forgotten call in previous PR
  src/zmb.sh
Labels: bug, fixed

#520 ZIP: `allows any file` (option)
  src/zmb.sh
Labels: ZipSigner, AK3

#521 DOC: Updates Toolchain Selection (settings)
  etc/settings.cfg
Labels: documentation
