Repository grm34/ZenMaxBuilder, pull requests merged in 2022-06, with the labels that each got.

#522 Kernel: adds alternative configuration commands
  SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: enhancement, make cmd, testing

#527 Updates AK3 Banner (ZMB v2.2)
  docs/ak3/banner
Labels: AK3

#528 Adds option to change AK3 Banner (FLASH)
  etc/settings.cfg
  src/zmb.sh
Labels: settings, AK3

#529 Match architecture to validate kernel path (CFG)
  SECURITY.md
  src/zmb.sh
Labels: settings

#530 Displays compilation information [--list option]
  SECURITY.md
  src/zmb.sh
Labels: main, testing

#534 Prevent running as single file [MAIN]
  src/zmb.sh
Labels: main

#535 Prevent missing language file [MAIN]
  SECURITY.md
  src/zmb.sh
Labels: main

#538 Use of `find` rather than crap use of `ls` [MAIN]
  SECURITY.md
  src/zmb.sh
Labels: main

#541 Improves the output of command-line options
  SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: enhancement

#542 Improves user inputs logging (cleaner logs)
  SECURITY.md
  etc/patterns.cfg
  src/zmb.sh
Labels: logs

#543 Updates ZMB Screenshots [--list]
  docs/assets/images/help.png
Labels: documentation

#547 Rewrite zmb sections (MAIN)
  SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: main

#548 Returns error on failed make kernelversion
  SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: Makefile, make cmd

#549 LOGS: Fix user inputs on interrupt (make)
  SECURITY.md
  src/zmb.sh
Labels: bug, fixed, logs

#552 Split functions (device folder and settings check)
  src/zmb.sh
Labels: main

#553 Fix code comments typo (CS)
  etc/settings.cfg
  src/zmb.sh
Labels: documentation

#554 LANG: rearranges strings alphabetically [CFG]
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
Labels: translation

#555 LANG: Auto adds strings to various translations
  src/translate.sh
Labels: enhancement, translation

#556 TRANSLATE: removes `quote` to allow splitting
  src/translate.sh
Labels: translation

#559 Updates Contributing Guidelines [TRANSLATE]
  .github/CONTRIBUTING.md
Labels: documentation

#561 TRAD: Auto translate strings 🏁
  .github/CONTRIBUTING.md
  src/translate.sh
Labels: translation, translate script

#564 Improved language (de.cfg)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/translate.sh
  src/zmb.sh
Labels: enhancement, translation, fixed, main

#565 Rewrite TimeZone auto-detect for performance
  src/zmb.sh
Labels: main

#566 DOC: Updates readme, index, security (v2.3)
  README.md
  SECURITY.md
  docs/index.md
Labels: documentation

#567 LANG: Fix forgotten VAR names from #564
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: translation

#568 DOC: Adds Naming Convention (Code Style)
  .github/CONTRIBUTING.md
  src/zmb.sh
Labels: documentation

#570 DOC: Updates Naming Convention (CS)
  SECURITY.md
  src/zmb.sh
Labels: documentation

#571 Reduces sourcing on startup (patterns)
  src/zmb.sh
Labels: telegram, main

#572 Removes useless function (patterns)
  SECURITY.md
  src/zmb.sh
Labels: telegram, main

#573 Rearranges main sections order (FUNC)
  src/zmb.sh
Labels: main

#574 DOC: Improves main sections names (CS)
  src/zmb.sh
Labels: documentation

#576 DOC: Adds missing commits badge url (MD)
  README.md
Labels: documentation

#577 DOC: Improves Code Comments (CS)
  .github/SECURITY.md
  src/translate.sh
  src/zmb.sh
Labels: documentation

#579 Fix forgotten locals (starter)
  .github/SECURITY.md
  src/zmb.sh
Labels: main

#580 CONF: save user settings as `user.cfg_bak` (up)
  .gitignore
  src/zmb.sh
Labels: documentation, settings

#581 SH: removes unwanted POSIX mode (bashvar)
  .github/SECURITY.md
  etc/excluded.cfg
  etc/patterns.cfg
  etc/telegram.cfg
  src/translate.sh
  src/zmb.sh
Labels: main

#582 DOC: Updates Code Comments (logs)
  src/zmb.sh
Labels: documentation

#583 LOGS: subshell no more required without POSIX (set)
  src/zmb.sh
Labels: main

#584 Grabs shell variables and func before TimeZone
  src/zmb.sh
Labels: main, logs

#585 GH: Updates Contributing Guidelines (CS)
  .github/CONTRIBUTING.md
Labels: documentation

#586 GH: Fix typo (Contributing)
  .github/CONTRIBUTING.md
Labels: documentation

#587 SETTINGS: Updates Instructions (clean)
  etc/settings.cfg
Labels: documentation, settings

#588 REGEX: prevents false positive by matching end
  src/zmb.sh
Labels: main

#589 Checks OS first for shells without $BASH_* (...)
  src/zmb.sh
Labels: main

#592 DOC: Updates Code Comments (CS)
  src/translate.sh
Labels: documentation, translate script

#594 DOC: Rewrites Code Comments (CS)
  .github/SECURITY.md
  src/translate.sh
  src/zmb.sh
Labels: documentation, main

#595 DOC: Fix some typo (CS)
  src/zmb.sh
Labels: documentation

#596 TERM: Updates colors checking (VAR)
  src/zmb.sh
Labels: main

#597 GHP: Updates `_config.yml` (tagline)
  docs/_config.yml
Labels: website

#598 Revert "GHP: Updates `_config.yml` (tagline)"
  docs/_config.yml
Labels: invalid

#599 LANG: Fix duplicate string name (WARN_TAG)
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: bug, translation, fixed

#601 TRANSLATE: Use of `realpath` (CFG)
  src/translate.sh
Labels: translate script

#602 TRANSLATE: rm TERM size checking (useless here)
  src/translate.sh
Labels: translate script

#603 TESTS: Adds pending test files (main)
  .github/FUNDING.yml
  .gitignore
  tests/test.sh
Labels: testing

#604 TESTING: adds device specs (jq)
  tests/test.sh
Labels: testing

#605 TESTING: adds more device specs (json)
  tests/test.sh
Labels: testing

#606 ZMB: Adds option to get device specifications (API)
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  README.md
  docs/assets/images/devices.png
  docs/index.md
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/translate.sh
  src/zmb.sh
  tests/device_specs.sh
Labels: enhancement, main, waiting approval

#608 TG: Fix `send_message` (quotes no more required)
  .github/SECURITY.md
  src/zmb.sh
Labels: bug, telegram, fixed

#611 AOSP: No need to delete `tgz` here (install)
  .github/SECURITY.md
  src/zmb.sh
Labels: main, AOSP-Clang

#612 PERF: `break` while `case` can stop iterating
  src/zmb.sh
Labels: main

#615 MAIN: `grep` rather than `sed` (Makefile CC)
  src/zmb.sh
Labels: main, Makefile

#616 GREP: rm `no-message` to get output on `ERR`
  src/zmb.sh
Labels: main, Makefile

#617 SED: rm the match of `?` (Makefile CC)
  src/zmb.sh
Labels: main, Makefile

#618 MAIN: Improves `CROSS_COMPILE` management
  .github/SECURITY.md
  src/zmb.sh
Labels: main, Makefile

#619 MAIN: really improves `CROSS_COMPILE` management
  src/zmb.sh
Labels: main, Makefile

#620 Allows `CROSS_COMPILE` to be defined as CMD ARG
  .github/SECURITY.md
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/zmb.sh
Labels: bug, fixed, Makefile

#621 DOC: Updates project overview (MD)
  README.md
  docs/index.md
Labels: documentation

#622 MAIN: fix `CC` detection (regex)
  src/zmb.sh
Labels: bug, fixed, Makefile

#623 MAIN: More implicit `function` name (command)
  .github/CONTRIBUTING.md
  src/zmb.sh
Labels: main

#624 DOC: updates project badges (distros)
  README.md
  docs/index.md
Labels: documentation

#625 DOC: updates toolchains overview (MD)
  README.md
  docs/index.md
Labels: documentation

#626 UPDATER: ensures `git` repository (TC)
  README.md
  docs/index.md
  src/zmb.sh
Labels: toolchains, main

#627 DOC: Adds more distro badges (MD)
  README.md
  docs/index.md
Labels: documentation

#628 MAIN: prevents bad use of `--` as cmd-line ARG
  .github/SECURITY.md
  src/zmb.sh
Labels: main

#629 MAIN: fix `TZ` detection on non init system
  .github/SECURITY.md
  src/zmb.sh
Labels: main

#630 ASCII: Unified banner for shell characters compatibility
  .github/SECURITY.md
  src/zmb.sh
Labels: bug, fixed, main

#633 DOC: updates zmb screenshots (MD)
  docs/assets/images/banner.png
  docs/assets/images/help.png
  docs/assets/images/screenshot.png
Labels: documentation

#634 INSTALLER: handles freeBSD package manager
  src/zmb.sh
Labels: requirements

#635 DOC: updates distro badges urls (MD)
  .github/SECURITY.md
  README.md
  docs/index.md
Labels: documentation

#637 MAIN: updates `starting blocks` error msg
  src/zmb.sh
Labels: main

#638 DOC: updates naming convention (bash)
  .github/CONTRIBUTING.md
  src/zmb.sh
Labels: documentation

#639 DOC: adds common warnings and errors (MD)
  README.md
  docs/index.md
Labels: documentation, website

#640 DOC: setting name for better understanding (MD)
  README.md
  docs/index.md
Labels: documentation

#641 DOC: updates common warnings (MD)
  README.md
  docs/index.md
Labels: documentation

#642 DOC: fix misspelling (MD)
  README.md
  docs/index.md
Labels: documentation

#643 DOC: updates common errors (MD)
  README.md
  docs/index.md
Labels: documentation

#644 DOC: updates Termux badge (MD)
  README.md
  docs/index.md
Labels: documentation

#645 DOC: updates common warnings and errors (MD)
  README.md
  docs/index.md
Labels: documentation

#647 MAIN: Updates ZMB uninstaller (HOME)
  README.md
  docs/index.md
  src/install.sh
Labels: main, requirements

#648 MAIN: rm forgotten `set -u` (installer)
  src/install.sh
Labels: main, requirements

#650 MAIN: updates absolute path (installer)
  .github/SECURITY.md
  src/zmb.sh
Labels: main, installer

#651 MAIN: removes no more used symlinks (translate)
  .github/CONTRIBUTING.md
  src/translate.sh
  translate
  zmb
Labels: main, translate script

#654 DOC: updates shell options (shopt)
  src/translate.sh
  src/zmb.sh
Labels: documentation

#655 DOC: adds installer comments
  src/install.sh
Labels: documentation

#656 DOC: updates install command (url)
  README.md
  docs/index.md
  docs/zmb
Labels: documentation

#657 GHP: fix build deployment (web)
  README.md
  docs/index.md
  docs/install/zmb
Labels: website

#660 GHP: removes symlink (invalid)
  docs/.nojekyll
  docs/install
Labels: website, install script

#661 GHP: updates install script (DL)
  README.md
  docs/index.md
  docs/zmb
Labels: documentation

#662 DOC: updates project overview (MD)
  README.md
  docs/index.md
Labels: documentation, website

#663 DOC: updates contributing guidelines (translate)
  .github/CONTRIBUTING.md
Labels: documentation

#664 INSTALL: hardlink rather than symlink (fix)
  src/install.sh
Labels: install script

#667 DOC: upates distro badges (FreeBSD)
  README.md
  docs/index.md
Labels: documentation

#668 INSTALLER: `chmod +x` required here (hardlink)
  src/install.sh
Labels: install script

#669 INSTALLER: fix required permissions (chmod)
  src/install.sh
Labels: install script

#670 TESTS: adds more controllers (whoami)
  tests/compat.sh
Labels: tests

#672 INSTALLER: fix installer mirror (not updated)
  docs/zmb
Labels: bug, fixed, install script

#671 MAIN: dependencies management 2.0 (PERF)
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/installer.yml
  README.md
  docs/index.md
  docs/zmb
  etc/settings.cfg
  lang/de.cfg
  lang/en.cfg
  lang/es.cfg
  lang/fr.cfg
  src/install.sh
  src/zmb.sh
Labels: main, in progress, requirements, install script

#673 MAIN: fix forgotten tests prompt
  src/zmb.sh
Labels: bug, fixed

#674 DOC: updates terminal outputs (ncurses)
  src/install.sh
  src/zmb.sh
Labels: documentation

#675 GHA: updates Installer workflow (docs/zmb)
  .github/workflows/installer.yml
Labels: install script

#676 GHA: fix installer workflow (docs/zmb)
  .github/workflows/installer.yml
  docs/zmb
Labels: install script

#677 GHA: workflow on installer changes (docs/zmb)
  .github/workflows/installer.yml
Labels: install script

#678 GHA: creates PR on installer changes (docs/zmb)
  .github/workflows/installer.yml
Labels: install script

#679 DOC: updates installer comments (dep)
  src/install.sh
Labels: documentation, install script

#682 GHA: updates automerge workflow (title)
  .github/workflows/automerge.yml
  .github/workflows/codacy.yml
Labels: automerge

#683 GHA: workflow update method (automerge)
  .github/workflows/automerge.yml
Labels: automerge

#684 GHA: updates `gh pr create` options (fill)
  .github/workflows/installer.yml
Labels: automerge

#685 INSTALLER: adds `checking the installation`
  README.md
  docs/index.md
  src/install.sh
Labels: install script

#688 DOC: updates installation instructions (MD)
  README.md
  docs/index.md
Labels: documentation

#689 DOC: fix forgotten changes (install)
  docs/index.md
Labels: documentation

#691 INSTALLER: fix `PREFIX` path (usr/bin)
  src/install.sh
Labels: install script

#694 DOC: updates installer comments (case)
  src/install.sh
Labels: documentation

#697 INSTALLER: rm useless declaration (confirm)
  src/install.sh
Labels: install script

#700 INSTALLER: adds MIT License (src)
  src/install.sh
Labels: documentation, install script

#703 DOC: updates installer comments (main)
  src/install.sh
Labels: documentation, install script

#705 DOC: adds installer options comments (install)
  src/install.sh
Labels: documentation, install script

#707 AK3: updates zmb banner (ASCII)
  docs/ak3/banner
Labels: AK3

#708 AK3: unified zmb banner (ASCii)
  docs/ak3/banner
Labels: AK3
